package com.fundbridge.walletservice.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fundbridge.walletservice.config.WalletProperties;
import org.springframework.stereotype.Service;

import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@Service
public class EncryptionService {

    private static final String TRANSFORMATION = "AES/GCM/NoPadding";
    private static final String KEY_ALGORITHM = "AES";
    private static final int KEY_LENGTH_BYTES = 32; // 256-bit
    private static final int IV_LENGTH_BYTES = 12;
    private static final int GCM_TAG_LENGTH_BITS = 128;

    private final SecretKey secretKey;
    private final SecureRandom secureRandom = new SecureRandom();
    private final ObjectMapper objectMapper = new ObjectMapper();

    public EncryptionService(WalletProperties walletProperties) {
        String base64Key = walletProperties.getDataEncryptionKey();
        if (base64Key == null || base64Key.isBlank()) {
            this.secretKey = null;
        } else {
            byte[] keyBytes = Base64.getDecoder().decode(base64Key);
            if (keyBytes.length != KEY_LENGTH_BYTES) {
                throw new IllegalArgumentException("DATA_ENCRYPTION_KEY must be a base64-encoded 256-bit key");
            }
            this.secretKey = new SecretKeySpec(keyBytes, KEY_ALGORITHM);
        }
    }

    public boolean isEnabled() {
        return secretKey != null;
    }

    /**
     * Encrypts plaintext with optional AAD. Returns JSON string containing iv, ciphertext, tag, aad, and alg.
     */
    public String encrypt(String plaintext, String aad) {
        if (plaintext == null) {
            return null;
        }
        if (!isEnabled()) {
            throw new IllegalStateException("Encryption requested but DATA_ENCRYPTION_KEY is not configured");
        }
        try {
            byte[] iv = new byte[IV_LENGTH_BYTES];
            secureRandom.nextBytes(iv);

            Cipher cipher = Cipher.getInstance(TRANSFORMATION);
            GCMParameterSpec spec = new GCMParameterSpec(GCM_TAG_LENGTH_BITS, iv);
            cipher.init(Cipher.ENCRYPT_MODE, Objects.requireNonNull(secretKey), spec);
            if (aad != null && !aad.isBlank()) {
                cipher.updateAAD(aad.getBytes(StandardCharsets.UTF_8));
            }
            byte[] cipherAndTag = cipher.doFinal(plaintext.getBytes(StandardCharsets.UTF_8));
            int tagLengthBytes = GCM_TAG_LENGTH_BITS / 8;
            int cipherLength = cipherAndTag.length - tagLengthBytes;
            byte[] cipherBytes = new byte[cipherLength];
            byte[] tagBytes = new byte[tagLengthBytes];
            System.arraycopy(cipherAndTag, 0, cipherBytes, 0, cipherLength);
            System.arraycopy(cipherAndTag, cipherLength, tagBytes, 0, tagLengthBytes);

            Map<String, Object> payload = new HashMap<>();
            payload.put("alg", "AES-256-GCM");
            payload.put("iv", Base64.getEncoder().encodeToString(iv));
            payload.put("ciphertext", Base64.getEncoder().encodeToString(cipherBytes));
            payload.put("tag", Base64.getEncoder().encodeToString(tagBytes));
            if (aad != null && !aad.isBlank()) {
                payload.put("aad", aad);
            }
            return objectMapper.writeValueAsString(payload);
        } catch (Exception e) {
            throw new IllegalStateException("Failed to encrypt metadata", e);
        }
    }

    /**
     * Decrypts payload generated by encrypt().
     */
    public String decrypt(String payload, String expectedAad) {
        if (payload == null || !isEnabled()) {
            return payload;
        }
        try {
            Map<?, ?> data = objectMapper.readValue(payload, Map.class);
            byte[] iv = Base64.getDecoder().decode((String) data.get("iv"));
            byte[] cipherBytes = Base64.getDecoder().decode((String) data.get("ciphertext"));
            byte[] tagBytes = Base64.getDecoder().decode((String) data.get("tag"));
            String aad = (String) data.get("aad");

            if (expectedAad != null && aad != null && !expectedAad.equals(aad)) {
                throw new IllegalStateException("AAD mismatch during decryption");
            }

            byte[] cipherAndTag = new byte[cipherBytes.length + tagBytes.length];
            System.arraycopy(cipherBytes, 0, cipherAndTag, 0, cipherBytes.length);
            System.arraycopy(tagBytes, 0, cipherAndTag, cipherBytes.length, tagBytes.length);

            Cipher cipher = Cipher.getInstance(TRANSFORMATION);
            GCMParameterSpec spec = new GCMParameterSpec(GCM_TAG_LENGTH_BITS, iv);
            cipher.init(Cipher.DECRYPT_MODE, Objects.requireNonNull(secretKey), spec);
            if (aad != null && !aad.isBlank()) {
                cipher.updateAAD(aad.getBytes(StandardCharsets.UTF_8));
            }
            byte[] plainBytes = cipher.doFinal(cipherAndTag);
            return new String(plainBytes, StandardCharsets.UTF_8);
        } catch (JsonProcessingException e) {
            throw new IllegalStateException("Encrypted metadata is malformed", e);
        } catch (Exception e) {
            throw new IllegalStateException("Failed to decrypt metadata", e);
        }
    }
}
